//API ref
export const GET_API_REF = 'GET_API_REF';
//Banner
export const GET_LIST_BANNER_REQUEST = 'GET_LIST_BANNER_REQUEST';
export const GET_LIST_BANNER_SUCCESS = 'GET_LIST_BANNER_SUCCESS';
export const GET_LIST_BANNER_FAILURE = 'GET_LIST_BANNER_FAILURE';

//Categories
export const GET_LIST_CATEGORIES_REQUEST = 'GET_LIST_CATEGORIES_REQUEST';
export const GET_LIST_CATEGORIES_SUCCESS = 'GET_LIST_CATEGORIES_SUCCESS';
export const GET_LIST_CATEGORIES_FAILURE = 'GET_LIST_CATEGORIES_FAILURE';

export const CHANGE_SELECTED_CATEGORY = 'CHANGE_SELECTED_CATEGORY';

//Products
export const GET_LIST_PRODUCTS_REQUEST = 'GET_LIST_PRODUCTS_REQUEST';
export const GET_LIST_PRODUCTS_SUCCESS = 'GET_LIST_PRODUCTS_SUCCESS';
export const GET_LIST_PRODUCTS_FAILURE = 'GET_LIST_PRODUCTS_FAILURE';
